name: 'Deploy to gh-pages'
on:
  push:
    branches:
      - master
    paths:
      - 'Documentation~/**'

jobs:
  deploy:
    name: Push docs to gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: Documentation~
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
