apiRules:
  - exclude:
      uidRegex: ^System
  - exclude:
      uidRegex: ^UnityEngine
  - exclude:
      uidRegex: ^UnityEditor
  - exclude:
      # inherited Object methods
      uidRegex: ^System\.Object\..*$
      type: Method
  - exclude:
      hasAttribute:
        uid: System.ObsoleteAttribute
      type: Type
