using UnityEngine;
using System.Collections.Generic;
using UnityEngine.InputSystem;

namespace IVLab.MinVR3 {

    /* Genertates fake VREvents for 3 trackers (usually assigned to the head and 2 hands).  This is similar to the 
	 * XR Device Simulator provided with Unity's XR Interaction Toolkit, but this is a simpler simulator and has better
	 * mouse and keyboard controls (IMHO).
	 * 
	 * This is only intended to be used while debugging and testing; not for an actual deployed VR app!
	 * 
	 * To make debugging VR apps easier, you can use the mouse and keyboard to create 'fake' input for two trackers.
	 * "Press the '1' or '2' key to switch between controlling tracker1 or tracker2. Move the mouse around the screen
	 * to move the 3D position of that tracker within a plane parallel to the screen.  Hold down 'left shift' while
	 * moving the mouse vertically to change the 3D depth. Hold 'x', 'y', or 'z' while moving the mouse horizontally
	 * to rotate the tracker around the X, Y, or Z axis.
	 * 
	 * Move the head around with the arrow keys.
	 */
    [AddComponentMenu("MinVR/Debug/Fake Tracking Input")]
    public class FakeTrackingInput : MonoBehaviour, IVREventProducer {
        [Header("Head Tracker")]
        [Tooltip("Fake head tracking with arrow keys. 'up' moves forward, 'down' moves backward, 'left' rotates left, 'right' rotates right.")]
        public string headTrackerBaseName = "FakeHeadTracker";

        public Vector3 initialHeadPos = new Vector3(0, 1, -2);
        private Vector3 headTrackerPos;

        public Vector3 initialHeadRot = new Vector3();
        private Quaternion headTrackerRot;

        [Header("Tracker #1")]
        [Tooltip("Base name of the VREvent generated by the first fake tracker.")]
        public string tracker1BaseName = "FakeTracker1";

        public Vector3 initialTracker1Pos = new Vector3(0, 0, 0);
        private Vector3 tracker1Pos;
        public Vector3 initialTracker1Rot = new Vector3();
        private Quaternion tracker1Rot;

        [Header("Tracker #2")]
        [Tooltip("Base name of the VREvent generated by the second fake tracker.")]
        public string tracker2BaseName = "FakeTracker2";

        public Vector3 initialTracker2Pos = new Vector3(0, 0, 0);
        private Vector3 tracker2Pos;
        public Vector3 initialTracker2Rot = new Vector3();
        private Quaternion tracker2Rot;

        private int curTracker = 0;
        private float lastx = float.NaN;
        private float lasty = float.NaN;


        private void OnEnable()
        {
            VREngine.instance.eventManager.AddEventProducer(this);
        }

        private void OnDisable()
        {
            VREngine.instance?.eventManager?.RemoveEventProducer(this);
        }

        void Start() {
            headTrackerPos = initialHeadPos;
            headTrackerRot = Quaternion.Euler(initialHeadRot);
            tracker1Pos = initialTracker1Pos;
            tracker1Rot = Quaternion.Euler(initialTracker1Rot);
            tracker2Pos = initialTracker2Pos;
            tracker2Rot = Quaternion.Euler(initialTracker1Rot);
        }

        void Update()
        {
            QueueHeadTrackerEvents();
            QueueRegularTrackerEvents();
        }

        private void QueueHeadTrackerEvents() {
            bool sendEvent = false;

            if (Keyboard.current[Key.UpArrow].isPressed) {
                sendEvent = true;
                headTrackerPos += 0.1f * Camera.main.transform.forward;
            }
            else if (Keyboard.current[Key.DownArrow].isPressed) {
                sendEvent = true;
                headTrackerPos -= 0.1f * Camera.main.transform.forward;
            }
            else if (Keyboard.current[Key.LeftArrow].isPressed) {
                sendEvent = true;
                headTrackerRot *= Quaternion.AngleAxis(-1.0f, new Vector3(0f, 1f, 0f));
            }
            else if (Keyboard.current[Key.RightArrow].isPressed) {
                sendEvent = true;
                headTrackerRot *= Quaternion.AngleAxis(1.0f, new Vector3(0f, 1f, 0f));
            }

            if (sendEvent) {
                VREngine.instance.eventManager.QueueEvent(headTrackerBaseName + "/Position", headTrackerPos);
                VREngine.instance.eventManager.QueueEvent(headTrackerBaseName + "/Rotation", headTrackerRot);
            }
        }


        private void QueueRegularTrackerEvents() {
            float x = Mouse.current.position.ReadValue().x;
            float y = Mouse.current.position.ReadValue().y;

            // first time through
            if (float.IsNaN(lastx)) {
                lastx = x;
                lasty = y;
                return;
            }

            bool sendEvent = false;

            if (Keyboard.current[Key.Digit1].wasPressedThisFrame) {
                curTracker = 0;
            } else if (Keyboard.current[Key.Digit2].wasPressedThisFrame) {
                curTracker = 1;
            }

            if (Keyboard.current[Key.X].isPressed) {
                float angle = 0.1f * (x - lastx);
                sendEvent = (angle != 0.0);
                if (curTracker == 0) {
                    tracker1Rot = Quaternion.AngleAxis(angle, new Vector3(1f, 0f, 0f)) * tracker1Rot;
                } else if (curTracker == 1) {
                    tracker2Rot = Quaternion.AngleAxis(angle, new Vector3(1f, 0f, 0f)) * tracker2Rot;
                }
            } else if (Keyboard.current[Key.Y].isPressed) {
                float angle = 0.1f * (x - lastx);
                sendEvent = (angle != 0.0);
                if (curTracker == 0) {
                    tracker1Rot = Quaternion.AngleAxis(angle, new Vector3(0f, 1f, 0f)) * tracker1Rot;
                } else if (curTracker == 1) {
                    tracker2Rot = Quaternion.AngleAxis(angle, new Vector3(0f, 1f, 0f)) * tracker2Rot;
                }
            } else if (Keyboard.current[Key.Z].isPressed) {
                float angle = 0.1f * (x - lastx);
                sendEvent = (angle != 0.0);
                if (curTracker == 0) {
                    tracker1Rot = Quaternion.AngleAxis(angle, new Vector3(0f, 0f, 1f)) * tracker1Rot;
                } else if (curTracker == 1) {
                    tracker2Rot = Quaternion.AngleAxis(angle, new Vector3(0f, 0f, 1f)) * tracker2Rot;
                }
            } else if (Keyboard.current[Key.LeftShift].isPressed) {
                float depth = 0.005f * (y - lasty);
                sendEvent = (depth != 0.0);
                if (curTracker == 0) {
                    tracker1Pos += depth * Camera.main.transform.forward;
                } else if (curTracker == 1) {
                    tracker2Pos += depth * Camera.main.transform.forward;
                }
            } else {
                sendEvent = (x != lastx) || (y != lasty);
                Ray ray = Camera.main.ScreenPointToRay(new Vector3(x, y, 0f));
                Plane p = new Plane();
                float dist = 0.0f;
                if (curTracker == 0) {
                    p.SetNormalAndPosition(-Camera.main.transform.forward, tracker1Pos);
                    if (p.Raycast(ray, out dist)) {
                        tracker1Pos = ray.GetPoint(dist);
                    }
                } else if (curTracker == 1) {
                    p.SetNormalAndPosition(-Camera.main.transform.forward, tracker2Pos);
                    if (p.Raycast(ray, out dist)) {
                        tracker2Pos = ray.GetPoint(dist);
                    }
                }

            }

            if (sendEvent) {
                if (curTracker == 0) {
                    VREngine.instance.eventManager.QueueEvent(tracker1BaseName + "/Position", tracker1Pos);
                    VREngine.instance.eventManager.QueueEvent(tracker1BaseName + "/Rotation", tracker1Rot);
                } else if (curTracker == 1) {
                    VREngine.instance.eventManager.QueueEvent(tracker2BaseName + "/Position", tracker2Pos);
                    VREngine.instance.eventManager.QueueEvent(tracker2BaseName + "/Rotation", tracker2Rot);
                }
            }

            this.lastx = x;
            this.lasty = y;
        }

        public List<IVREventPrototype> GetEventPrototypes()
        {
            List<IVREventPrototype> allEvents = new List<IVREventPrototype>();
            allEvents.Add(new VREventPrototype<Vector3>(headTrackerBaseName + "/Position"));
            allEvents.Add(new VREventPrototype<Quaternion>(headTrackerBaseName + "/Rotation"));

            allEvents.Add(new VREventPrototype<Vector3>(tracker1BaseName + "/Position"));
            allEvents.Add(new VREventPrototype<Quaternion>(tracker1BaseName + "/Rotation"));

            allEvents.Add(new VREventPrototype<Vector3>(tracker2BaseName + "/Position"));
            allEvents.Add(new VREventPrototype<Quaternion>(tracker2BaseName + "/Rotation"));

            return allEvents;
        }
    }

} // namespace
